### ISSUE TITLE
Backgrounds0 crashes

### ISSUE THREAD

**Issue by StixV50** [KRHS-Game-Programming-2022/Rhythm-Smash#1]
when trying to play with the first background it crashes, log below:

bg0 0 Backgrounds/Background 0.png
Backgrounds/Background 0.png
Traceback (most recent call last):
  File "Main.py", line 188, in <module>
    bgImage = pygame.image.load(backgroundSelected)
pygame.error: Couldn't open Backgrounds/Background 0.png

**Comment by Tshep9** [comment]
Fixed it (file was name Background.png instead of Background 0.png).

5/5/22 at 9:14 am
